name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  call-validate:
    uses: INENI-PT-Muehlbacher-GroupB/.github/.github/workflows/pr-title-reusable.yml@main